### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by andrey-utkin** [termux/termux-packages#9975]
### Problem description

I have Termux installed from F-Droid up to date.
Last time I did `pkg upgrade` was last Monday.
Today I got this several times, but somehow after a few times it passed that point successfully without this error.
```
Testing the available mirrors:
[*] https://mirror.mwt.me/termux/main: ok
[*] https://termux.sahilister.in/apt/termux-main: ok
[*] https://plug-mirror.rcac.purdue.edu/termux/termux-main: ok
[*] https://termux.mentality.rip/termux-main: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://termux.librehat.com/apt/termux-main: ok
[*] https://termux.astra.in.ua/apt/termux-main: ok
[*] https://packages-cf.termux.org/apt/termux-main: ok
[*] https://dl.kcubeterm.com/termux-main: ok
/data/data/com.termux/files/usr/bin/pkg: line 136: mirrors[$w]: unbound variable
```

### What steps will reproduce the bug?

`pkg upgrade`

### What is the expected behavior?

Successful 

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
Updatable packages:
curl/stable 7.82.0-1 aarch64 [upgradable from: 7.82.0]
gzip/stable 1.12 aarch64 [upgradable from: 1.11-3]
libcurl/stable 7.82.0-1 aarch64 [upgradable from: 7.82.0]
libgpg-error/stable 1.45 aarch64 [upgradable from: 1.43]
libusb/stable 1.0.26 aarch64 [upgradable from: 1.0.25]
termux-keyring/stable,stable 3.1 all [upgradable from: 3.0]
termux-tools/stable,stable 0.173 all [upgradable from: 0.171]
unbound/stable 1.15.0 aarch64 [upgradable from: 1.13.2-3]
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.71-perf-gf527b70 #1 SMP PREEMPT Tue Feb 26 12:12:42 CST 2019 aarch64 Android
Device manufacturer:
Lenovo
Device model:
Lenovo K520
```

**Comment by Querela** [comment]
Ok. I got this today, too. I don't update daily but was the first occurrence for me. Just to add some more datapoints for this issue ...
`termux-info`: 
```yaml
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf-g4b73fd3 #2 SMP PREEMPT Sun Jun 27 00:46:38 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
MI 9
```
